Repository Clinical-Genomics/cg, pull requests merged in 2020-02, with the labels that each got.

#531 Use cg.utils.commands in VogueApi
  cg/apps/vogue.py
Labels: bug, effort low, gain medium

#492 styling requests from VW
  cg/apps/invoice/render.py
  cg/apps/invoice/templates/KI_pool_invoice.xlsx
  cg/apps/invoice/templates/KI_sample_invoice.xlsx
  cg/apps/invoice/templates/KTH_pool_invoice.xlsx
  cg/apps/invoice/templates/KTH_sample_invoice.xlsx
  cg/apps/invoice/templates/pool_invoice.xlsx
  cg/apps/invoice/templates/sample_invoice.xlsx
  cg/meta/invoice.py
Labels: effort medium, gain medium

#542 Mip dna v8.2
  README.md
  cg/apps/tb/add.py
  cg/cli/upload/upload.py
  cg/cli/workflow/balsamic/base.py
  cg/cli/workflow/balsamic/deliver.py
  cg/cli/workflow/microsalt/base.py
  cg/cli/workflow/microsalt/deliver.py
  cg/cli/workflow/mip_dna/base.py
  cg/cli/workflow/mip_dna/deliver.py
  cg/cli/workflow/mip_rna/base.py
  cg/cli/workflow/mip_rna/deliver.py
  cg/meta/deliver.py
  cg/meta/deliver/__init__.py
  cg/meta/deliver/balsamic.py
  cg/meta/deliver/microsalt.py
  cg/meta/deliver/mip_dna.py
  cg/meta/deliver/mip_rna.py
  cg/meta/upload/scoutapi.py
  cg/meta/workflow/balsamic.py
  cg/meta/workflow/mip_dna.py
  cg/meta/workflow/mip_rna.py
  tests/apps/tb/mip/test_get_files.py
  tests/fixtures/apps/tb/case/case_qc_sample_info.yaml
  tests/meta/conftest.py
  tests/meta/deliver/test_delivery_api.py
  tests/meta/upload/conftest.py
  tests/meta/upload/test_meta_upload_scoutapi.py
Labels: effort medium, gain high, urgency medium
