Repository Clinical-Genomics/cg, pull requests merged in 2020-06, with the labels that each got.

#650 Vogue load bioinfo all
  cg/cli/upload/vogue.py
  cg/cli/workflow/balsamic/base.py
  cg/cli/workflow/get_links.py
  cg/cli/workflow/mip_dna/base.py
  cg/cli/workflow/mip_rna/base.py
  pyproject.toml
  tests/cli/workflow/conftest.py
  tests/cli/workflow/test_get_links.py
  tests/store_helpers.py
Labels: Effort M, Gain L, Urgency L

#659 Feat/balsamic mode select
  cg/apps/balsamic/api.py
  cg/cli/workflow/balsamic/base.py
  tests/cli/workflow/balsamic/conftest.py
  tests/cli/workflow/balsamic/test_run.py
Labels: Balsamic

#602 Spring compression
  .github/workflows/lint_and_install.yml
  cg/apps/crunchy.py
  cg/apps/crunchy/__init__.py
  cg/apps/crunchy/crunchy.py
  cg/apps/crunchy/models.py
  cg/apps/crunchy/sbatch.py
  cg/cli/base.py
  cg/cli/compress.py
  cg/cli/compress/__init__.py
  cg/cli/compress/bam.py
  cg/cli/compress/base.py
  cg/cli/compress/fastq.py
  cg/cli/compress/helpers.py
  cg/cli/store.py
  cg/constants.py
  cg/meta/compress.py
  cg/meta/compress/__init__.py
  cg/meta/compress/compress.py
  cg/meta/compress/files.py
  cg/store/get/__init__.py
  cg/store/get/cases.py
  cg/utils/date.py
  requirements.txt
  tests/apps/crunchy/conftest.py
  tests/apps/crunchy/test_compress_bam.py
  tests/apps/crunchy/test_compress_fastq.py
  tests/apps/crunchy/test_config.py
  tests/apps/crunchy/test_crunchy.py
  tests/apps/crunchy/test_sbatch.py
  tests/cli/compress/conftest.py
  tests/cli/compress/test_cli_compress_fastq.py
  tests/cli/compress/test_cli_decompress_spring.py
  tests/conftest.py
  tests/fixtures/apps/crunchy/spring_metadata.json
  tests/meta/compress/conftest.py
  tests/meta/compress/test_clean_bam.py
  tests/meta/compress/test_clean_fastq.py
  tests/meta/compress/test_compress.py
  tests/meta/compress/test_compress_common.py
  tests/meta/compress/test_compress_files.py
  tests/meta/compress/test_compress_meta_bam.py
  tests/meta/compress/test_compress_meta_fastq.py
  tests/meta/compress/test_decompress_spring_meta.py
  tests/meta/conftest.py
  tests/meta/upload/conftest.py
  tests/mocks/crunchy.py
  tests/mocks/hk_mock.py
  tests/mocks/scout.py
  tests/store_helpers.py
Labels: Effort L, Gain L, Urgency L
