Repository Clinical-Genomics/cg, pull requests merged in 2020-03, with the labels that each got.

#513 Use `commands.Process` when running Madeline
  .travis.yml
  cg/apps/madeline.py
  cg/apps/madeline/__init__.py
  cg/apps/madeline/api.py
  cg/cli/upload/beacon.py
  cg/cli/upload/coverage.py
  cg/cli/upload/delivery.py
  cg/cli/upload/genotype.py
  cg/cli/upload/mutacc.py
  cg/cli/upload/observations.py
  cg/cli/upload/scout.py
  cg/cli/upload/upload.py
  cg/cli/upload/utils.py
  cg/cli/upload/validate.py
  cg/meta/upload/scoutapi.py
  tests/apps/madeline/conftest.py
  tests/apps/madeline/test_madeline.py
  tests/cli/upload/conftest.py
  tests/cli/upload/test_cli_upload.py
  tests/conftest.py
  tests/fixtures/apps/madeline/madeline.xml
  tests/meta/upload/conftest.py
Labels: gain low, small

#549 Update constants.py
  cg/apps/lims/api.py
  cg/apps/lims/constants.py
Labels: effort low, gain high

#595 Fix bug when generating madeline input and status is None
  cg/apps/madeline/api.py
  tests/apps/madeline/test_madeline.py
Labels: bugfix

#596 feat(cli_clean_rename): Renamed cli commands
  cg/cli/clean.py
Labels: effort low, gain medium, urgency low
