Repository Clinical-Genomics/cg, pull requests merged in 2021-02, with the labels that each got.

#844 Fluffy workflow start
  CHANGELOG.md
  cg/apps/lims/api.py
  cg/cli/workflow/base.py
  cg/cli/workflow/fluffy/__init__.py
  cg/cli/workflow/fluffy/base.py
  cg/meta/workflow/fluffy.py
  tests/cli/workflow/balsamic/conftest.py
  tests/cli/workflow/fluffy/conftest.py
  tests/cli/workflow/fluffy/test_cli_create_samplesheet.py
  tests/cli/workflow/fluffy/test_cli_link.py
  tests/cli/workflow/fluffy/test_cli_run.py
  tests/cli/workflow/fluffy/test_cli_start.py
  tests/cli/workflow/fluffy/test_cli_store.py
  tests/conftest.py
  tests/fixtures/apps/fluffy/SampleSheet.csv
  tests/fixtures/apps/fluffy/fluffy_fastq.fastq.gz
  tests/store_helpers.py
Labels: Effort M, Gain L, NIPT NovaSeq, Urgency S

#947 Feat(Applications): add covid prep category
  CHANGELOG.md
  cg/constants/constants.py
  scripts/add-covid-prep_category.sql
Labels: Effort M, Urgency M

#948 Fix(ordering): Remove faulty ticket message parts
  CHANGELOG.md
  cg/meta/orders/api.py
Labels: Bug, Effort S, Gain S

#957 State non mandatory fields as optional
  CHANGELOG.md
  cg/store/api/import_func.py
  cg/store/api/models.py
Labels: bugfix

#959 Set action to "analyze" for cases that decompression started for
  CHANGELOG.md
  cg/cli/workflow/mip_dna/base.py
Labels: Effort S, Gain M

#929 Feat(orders): support json mip orders with cohorts, phenotype_terms and synopsis
  CHANGELOG.md
  cg/apps/lims/limsjson.py
  cg/meta/orders/schema.py
  cg/meta/orders/status.py
  cg/server/api.py
  cg/store/models.py
  scripts/add-cohorts-synopsis-phenotype_terms-to-samples.sql
  tests/apps/lims/test_limsjson.py
  tests/fixtures/orders/balsamic.json
  tests/fixtures/orders/mip-json.json
  tests/fixtures/orders/mip.json
  tests/fixtures/orders/mip_rna.json
  tests/meta/orders/conftest.py
  tests/meta/orders/test_meta_orders_status.py
Labels: Enhancement

#928 Fetch flowcell from PDC: update destination server for novaseq flowcells
  .gitignore
  CHANGELOG.md
  alembic/README
  alembic/env.py
  alembic/script.py.mako
  alembic/versions/6d74453565f2_add_retrieved_status_to_flowcell_table.py
  cg/apps/pdc.py
  cg/constants/constants.py
  cg/meta/backup.py
  scripts/add-retrieved-status-to-flowcell.sql
  tests/meta/backup/test_meta_backup.py
Labels: Effort S, Gain L, demux migration

#974 feat(refactor): Use case id as positional arg in linking command
  CHANGELOG.md
  cg/cli/workflow/mip_dna/base.py
  cg/cli/workflow/mip_rna/base.py
  tests/cli/workflow/mip/test_cli_mip_rna_link.py
Labels: rna-results-in-scout
