Repository Clinical-Genomics/cg, pull requests merged in 2021-05, with the labels that each got.

#1154 raise on reused case name
  CHANGELOG.md
  cg/meta/orders/schema.py
  cg/meta/orders/status.py
  cg/server/api.py
  tests/meta/orders/test_meta_orders_status.py
Labels: Bug

#1152 Gisaid region fields
  CHANGELOG.md
  cg/cli/upload/gisaid.py
  cg/constants/lims.py
  cg/meta/upload/gisaid/gisaid.py
  cg/meta/upload/gisaid/models.py
  cg/models/cg_config.py
  tests/meta/upload/gisaid/__init__.py
  tests/meta/upload/gisaid/conftest.py
  tests/meta/upload/gisaid/fixtures/concat.fasta
  tests/meta/upload/gisaid/fixtures/four_samples.csv
  tests/meta/upload/gisaid/fixtures/invalid.fasta
  tests/meta/upload/gisaid/fixtures/s1_valid.fasta
  tests/meta/upload/gisaid/fixtures/s2_valid.fasta
  tests/meta/upload/gisaid/fixtures/s3_valid.fasta
  tests/meta/upload/gisaid/fixtures/s4_valid.fasta
  tests/meta/upload/gisaid/fixtures/valid.fasta
  tests/meta/upload/gisaid/test_gisaid_api.py
Labels: Effort S, Gain L

#1167 Deliver and rsync
  CHANGELOG.md
  cg/cli/deliver/base.py
  cg/meta/deliver_ticket.py
  tests/cli/deliver/test_deliver_base.py
  tests/meta/deliver/test_deliver_ticket.py
Labels: Gain L
