Repository Clinical-Genomics/cg, pull requests merged in 2021-04, with the labels that each got.

#1113 Fix scout finished cases
  CHANGELOG.md
  cg/cli/clean.py
  tests/cli/clean/test_clean_hk_bundle_files.py
Labels: bugfix

#1117 Feat: get family analysis
  CHANGELOG.md
  cg/cli/get.py
  tests/cli/get/test_cli_get_analysis.py
  tests/cli/get/test_cli_get_family.py
Labels: Enhancement

#1086 support for Gisaid upload
  CHANGELOG.md
  cg/cli/upload/base.py
  cg/cli/upload/gisaid.py
  cg/exc.py
  cg/meta/meta.py
  cg/meta/upload/gisaid/__init__.py
  cg/meta/upload/gisaid/constants.py
  cg/meta/upload/gisaid/gisaid.py
  cg/meta/upload/gisaid/models.py
  cg/meta/workflow/fastq.py
  cg/models/cg_config.py
  cg/store/api/findbusinessdata.py
  cg/store/models.py
  tests/meta/upload/gisaid/__init__.py
  tests/meta/upload/gisaid/conftest.py
  tests/meta/upload/gisaid/fixtures/concat.fasta
  tests/meta/upload/gisaid/fixtures/four_samples.csv
  tests/meta/upload/gisaid/fixtures/invalid.fasta
  tests/meta/upload/gisaid/fixtures/s1_valid.fasta
  tests/meta/upload/gisaid/fixtures/s2_valid.fasta
  tests/meta/upload/gisaid/fixtures/s3_valid.fasta
  tests/meta/upload/gisaid/fixtures/s4_valid.fasta
  tests/meta/upload/gisaid/fixtures/valid.fasta
  tests/meta/upload/gisaid/test_gisaid_api.py
Labels: Effort M, Gain L

#1124 Feat(admin): show customers in user view
  CHANGELOG.md
  cg/server/admin.py
Labels: Enhancement

#1141 Feat(Admin): show customer-group related customers
  CHANGELOG.md
  cg/server/admin.py
Labels: Enhancement
