Repository Clinical-Genomics/cg, pull requests merged in 2023-08, with the labels that each got.

#2288 add(force flag to new demux pp flow)
  cg/cli/demultiplex/finish.py
  cg/meta/demultiplex/demux_post_processing.py
  cg/meta/demultiplex/status_db_storage_functions.py
  cg/meta/demultiplex/validation.py
  tests/meta/demultiplex/test_validation.py
Labels: Project Task

#2295 add(samples to flow cell in new demux pp workflow)
  cg/meta/demultiplex/status_db_storage_functions.py
  tests/conftest.py
  tests/meta/demultiplex/test_status_db_storage_functions.py
  tests/store/api/test_base.py
Labels: Project Task

#2308 refactor(NfAnalysisAPI) avoid code duplication between rnafusion and taxprofiler
  cg/meta/workflow/nf_analysis.py
  cg/meta/workflow/rnafusion.py
Labels: Refactor

#2294 fix(uncouple statusDB Sample reads from CGstats)
  alembic/versions/201b16c45366_drop_calc_reads_columns.py
  cg/meta/demultiplex/status_db_storage_functions.py
  cg/meta/transfer/flowcell.py
  cg/store/models.py
  tests/conftest.py
  tests/meta/demultiplex/test_demux_post_processing.py
  tests/meta/demultiplex/test_status_db_storage_functions.py
Labels: Project Task

#2339 Fix validator for rnafusion
  cg/models/nf_analysis.py
  tests/models/rnafusion/conftest.py
  tests/models/rnafusion/test_rnafusion_sample.py
Labels: Bug

#2106 (feat taxprofiler): Add taxprofiler resolve-compression and run commands
  cg/cli/workflow/taxprofiler/base.py
  cg/cli/workflow/taxprofiler/taxprofiler_command.py
  cg/constants/nf_analysis.py
  cg/meta/workflow/nf_analysis.py
  cg/meta/workflow/rnafusion.py
  cg/meta/workflow/taxprofiler.py
  cg/models/cg_config.py
  cg/models/taxprofiler/taxprofiler.py
  cg/models/taxprofiler/taxprofiler_sample.py
  tests/cli/workflow/taxprofiler/conftest.py
  tests/cli/workflow/taxprofiler/test_cli_taxprofiler_run.py
  tests/conftest.py
Labels: cg, Project Task, taxprofiler

#2286 refactor(remove cgstats from delete demux api)
  cg/cli/demultiplex/demux.py
  cg/meta/demultiplex/delete_demultiplex_api.py
  tests/cli/demultiplex/test_demultiplex_flowcell.py
  tests/meta/demultiplex/test_delete_demultiplex_api.py
Labels: Project Task

#2343 Add sample sheet to housekeeper right after creation
  cg/apps/demultiplex/demultiplex_api.py
  cg/apps/housekeeper/hk.py
  cg/apps/slurm/slurm_api.py
  cg/cli/clean.py
  cg/cli/demultiplex/demux.py
  cg/cli/demultiplex/sample_sheet.py
  cg/meta/clean/flow_cell_run_directories.py
  cg/meta/demultiplex/delete_demultiplex_api.py
  cg/meta/demultiplex/demux_post_processing.py
  cg/meta/demultiplex/housekeeper_storage_functions.py
  cg/meta/demultiplex/utils.py
  cg/meta/workflow/fluffy.py
  cg/models/cg_config.py
  cg/models/demultiplex/demux_results.py
  tests/apps/demultiplex/test_demultiplex_api.py
  tests/cli/demultiplex/test_create_sample_sheet.py
  tests/cli/demultiplex/test_demultiplex_flowcell.py
  tests/cli/workflow/fluffy/conftest.py
  tests/conftest.py
  tests/meta/clean/test_remove_old_dirs.py
  tests/meta/demultiplex/test_delete_demultiplex_api.py
  tests/meta/demultiplex/test_housekeeper_storage_functions.py
  tests/meta/demultiplex/test_utils.py
Labels: cg, Project Task, backend

#2364 Patch path to sample sheet in hk
  cg/meta/demultiplex/demux_post_processing.py
  cg/meta/demultiplex/housekeeper_storage_functions.py
  cg/meta/demultiplex/status_db_storage_functions.py
  cg/models/demultiplex/flow_cell.py
  tests/meta/demultiplex/test_demux_post_processing.py
  tests/meta/demultiplex/test_housekeeper_storage_functions.py
Labels: Needs Refinement
