Repository Clinical-Genomics/cg, pull requests merged in 2023-12, with the labels that each got.

#2619 fix(demultiplexing )Remove demux dir before starting a new demux job
  cg/apps/demultiplex/demultiplex_api.py
  cg/cli/demultiplex/demux.py
  tests/apps/demultiplex/test_demultiplex_api.py
  tests/cli/demultiplex/test_demultiplex_flowcell.py
Labels: demultiplex

#2621 Update Rnafusion for release v3.0.1
  cg/constants/delivery.py
  cg/constants/scout_upload.py
  cg/meta/report/balsamic.py
  cg/meta/report/field_validators.py
  cg/meta/report/report_api.py
  cg/meta/report/rnafusion.py
  cg/meta/report/templates/balsamic_report.html
  cg/meta/report/templates/rnafusion_report.html
  cg/meta/upload/scout/hk_tags.py
  cg/meta/upload/scout/rnafusion_config_builder.py
  cg/meta/upload/scout/scout_config_builder.py
  cg/meta/workflow/nf_analysis.py
  cg/meta/workflow/rnafusion.py
  cg/models/nf_analysis.py
  cg/models/report/report.py
  cg/models/rnafusion/rnafusion.py
  cg/models/scout/scout_load_config.py
  cg/resources/rnafusion_bundle_filenames.csv
  tests/fixtures/analysis/rnafusion/multiqc_data.json
  tests/meta/report/conftest.py
  tests/meta/workflow/conftest.py
  tests/models/nextflow/test_nextflow_deliver.py
Labels: rnafusion

#2750 Add export managed variants
  cg/apps/scout/scoutapi.py
  cg/cli/upload/scout.py
  cg/cli/utils.py
  cg/cli/workflow/mip/base.py
  cg/cli/workflow/mip_dna/base.py
  cg/cli/workflow/raredisease/base.py
  cg/constants/scout.py
  cg/meta/report/balsamic.py
  cg/meta/report/balsamic_umi.py
  cg/meta/report/mip_dna.py
  cg/meta/report/rnafusion.py
  cg/meta/upload/scout/balsamic_config_builder.py
  cg/meta/upload/scout/balsamic_umi_config_builder.py
  cg/meta/upload/scout/mip_config_builder.py
  cg/meta/upload/scout/rnafusion_config_builder.py
  cg/meta/upload/scout/uploadscoutapi.py
  cg/meta/workflow/analysis.py
  cg/meta/workflow/mip.py
  cg/meta/workflow/mip_dna.py
  cg/meta/workflow/raredisease.py
  tests/cli/conftest.py
  tests/cli/workflow/mip/conftest.py
  tests/cli/workflow/mip/test_cli_mip_base.py
  tests/cli/workflow/mip/test_cli_mip_dna_manged_variants.py
  tests/cli/workflow/mip/test_cli_mip_dna_panel.py
  tests/cli/workflow/raredisease/test_cli_raredisease_compound_commands.py
  tests/meta/upload/scout/test_meta_upload_scoutapi_rna.py
Labels: Project Task

#2763 Refactor link fastq files
  cg/io/gzip.py
  cg/meta/workflow/analysis.py
  cg/meta/workflow/balsamic.py
  cg/meta/workflow/fastq.py
  cg/meta/workflow/microsalt.py
  cg/meta/workflow/mip.py
  cg/meta/workflow/mutant.py
  cg/meta/workflow/nf_analysis.py
  cg/meta/workflow/rnafusion.py
  cg/meta/workflow/taxprofiler.py
  cg/models/fastq.py
  tests/apps/mip/conftest.py
  tests/conftest.py
  tests/fixtures/io/casava_five_parts.fastq.gz
  tests/fixtures/io/casava_seven_parts.fastq.gz
  tests/fixtures/io/casava_ten_parts.fastq.gz
  tests/fixtures/io/example.gz
  tests/io/conftest.py
  tests/io/test_io_gzip.py
  tests/meta/workflow/test_analysis.py
  tests/meta/workflow/test_fastq.py
  tests/models/test_fastq.py
Labels: Enhancement, Project Task

#2775 feat(clean): Do not abort but continue
  cg/cli/clean.py
Labels: Bug

#2780 Refactor gender to sex
  cg/apps/scout/scout_export.py
  cg/apps/scout/validators.py
  cg/cli/add.py
  cg/cli/workflow/balsamic/options.py
  cg/constants/subject.py
  cg/meta/orders/metagenome_submitter.py
  cg/meta/orders/microbial_submitter.py
  cg/meta/upload/gt.py
  cg/meta/workflow/balsamic.py
  cg/models/mip/mip_metrics_deliverables.py
  cg/models/report/validators.py
  tests/apps/gt/conftest.py
  tests/apps/mip/conftest.py
  tests/apps/scout/conftest.py
  tests/apps/scout/test_scout_models.py
  tests/cli/add/test_cli_add_relationship.py
  tests/cli/add/test_cli_add_sample.py
  tests/cli/clean/conftest.py
  tests/cli/generate/report/conftest.py
  tests/cli/set/test_cli_set_list_keys.py
  tests/cli/set/test_cli_set_sample.py
  tests/cli/workflow/balsamic/conftest.py
  tests/cli/workflow/conftest.py
  tests/cli/workflow/fluffy/conftest.py
  tests/cli/workflow/mip/conftest.py
  tests/conftest.py
  tests/meta/archive/conftest.py
  tests/meta/clean/conftest.py
  tests/meta/conftest.py
  tests/meta/orders/test_SarsCov2Submitter_validate_order.py
  tests/meta/orders/test_meta_orders_api.py
  tests/meta/upload/conftest.py
  tests/meta/upload/mutacc/conftest.py
  tests/meta/upload/scout/conftest.py
  tests/meta/upload/scout/test_meta_upload_scoutapi_rna.py
  tests/meta/workflow/conftest.py
  tests/meta/workflow/test_balsamic.py
  tests/models/mip/test_mip_metrics_deliverables.py
  tests/models/report/test_validators.py
  tests/store/api/add/test_store_add_base.py
  tests/store/api/conftest.py
  tests/store/api/status/test_store_api_status_analysis.py
  tests/store/api/status/test_store_api_status_cases.py
  tests/store/conftest.py
  tests/store/filters/test_status_cases_filters.py
  tests/store/filters/test_status_samples_filters.py
  tests/store/test_delivery.py
  tests/store_helpers.py
  tests/utils/test_dispatcher.py
Labels: Enhancement
