Repository Clinical-Genomics/cg, pull requests merged in 2023-04, with the labels that each got.

#1884 fix(cg/meta/backup.py Nonetype.to_archive bug)
  cg/meta/backup/backup.py
  cg/meta/compress/compress.py
Labels: Project Task

#1890 Function dispatcher module
  cg/utils/dispatcher.py
  tests/utils/test_dispatcher.py
Labels: Project Task

#1892 bugFix(dispatch ignore self)
  cg/utils/dispatcher.py
  tests/utils/test_dispatcher.py
Labels: Project Task

#1888 refactor(get_analyses_before)
  cg/cli/clean.py
  cg/meta/clean/api.py
  cg/store/api/status.py
  cg/utils/dispatcher.py
  tests/cli/clean/test_hk_bundle_files.py
  tests/cli/clean/test_hk_case_bundle_files.py
  tests/store/api/status/test_store_api_status_analysis.py
  tests/utils/test_dispatcher.py
Labels: Project Task

#1733 feat(DDNApi) Adds a minimal API for communicating with DDN
  cg/exc.py
  cg/meta/archive/__init__.py
  cg/meta/archive/ddn_dataflow.py
  cg/models/cg_config.py
  tests/meta/archive/conftest.py
  tests/meta/archive/test_archiving.py
Labels: Project Task

#1903 Refactor family sample
  cg/meta/deliver.py
  cg/meta/orders/case_submitter.py
  cg/meta/report/mip_dna.py
  cg/meta/report/report_api.py
  cg/store/api/find_business_data.py
  cg/store/filters/status_application_version_filters.py
  cg/store/filters/status_case_sample_filters.py
  tests/conftest.py
  tests/meta/deliver/test_delivery_api.py
  tests/meta/report/conftest.py
  tests/store/api/conftest.py
  tests/store/api/delete/test_store_api_delete.py
  tests/store/api/find/test_find_business_data.py
  tests/store/conftest.py
  tests/store/filters/test_status_case_sample_filters.py
Labels: Project Task

#1898 refactor(analyses-to-deliver)
  cg/cli/upload/base.py
  cg/cli/upload/clinical_delivery.py
  cg/cli/upload/utils.py
  cg/server/api.py
  cg/store/api/base.py
  cg/store/api/status.py
  tests/store/api/conftest.py
  tests/store/api/find/test_find_business_data_analysis.py
  tests/store/api/status/test_store_api_status.py
Labels: Project Task

#1897 dispatcher-update
  cg/cli/clean.py
  cg/cli/upload/vogue.py
  cg/utils/dispatcher.py
  tests/utils/test_dispatcher.py
Labels: Project Task

#1915 Remove unused analyses get function
  cg/store/api/find_business_data.py
  tests/store/api/status/test_store_api_status.py
Labels: Project Task

#1922 Filter cases in past x days
  cg/server/api.py
  cg/store/api/find_business_data.py
  cg/store/api/status.py
  cg/store/filters/status_case_filters.py
  tests/store/api/find/test_find_business_data.py
  tests/store/filters/test_status_cases_filters.py
Labels: Project Task

#1924 Extract function for filtering not analysed cases associated with sample
  cg/meta/transfer/external_data.py
  cg/store/api/base.py
  cg/store/api/find_business_data.py
  cg/store/filters/status_case_filters.py
  cg/store/filters/status_sample_filters.py
  tests/store/api/find/test_find_business_data.py
  tests/store/filters/test_status_cases_filters.py
Labels: Project Task

#1911 refactor(get_samples_by_any_id)
  cg/store/api/find_business_data.py
  cg/store/filters/status_sample_filters.py
  tests/store/api/find/test_find_business_data_sample.py
  tests/store/conftest.py
  tests/store/filters/test_status_samples_filters.py
Labels: Project Task

#1929 Patch the cli command family
  cg/cli/set/families.py
Labels: Bug

#1921 Refactor case filtering
  cg/store/api/find_business_data.py
  cg/store/api/status.py
  cg/store/filters/status_case_filters.py
  tests/store/filters/test_status_cases_filters.py
Labels: Project Task

#1935 fix(get_flow_cells_by_statuses)
  cg/cli/clean.py
  cg/meta/backup/backup.py
  cg/store/api/find_business_data.py
  tests/cli/backup/test_backup_command.py
  tests/meta/backup/test_meta_backup.py
Labels: Project Task

#1932 Rename cli set command family to case
  cg/cli/set/base.py
  cg/cli/set/case.py
  cg/cli/set/cases.py
  tests/cli/delete/test_cli_delete_case.py
  tests/cli/delete/test_cli_delete_cases.py
  tests/cli/set/test_cli_set_case.py
  tests/cli/set/test_cli_set_cases.py
  tests/cli/set/test_cli_set_flowcell.py
  tests/cli/set/test_cli_set_list_keys.py
  tests/cli/set/test_cli_set_sample.py
  tests/cli/set/test_cli_set_samples.py
  tests/cli/set/test_families.py
  tests/cli/set/test_family.py
Labels: Project Task

#1938 fix(get_flow_cells_by_case)
  cg/store/api/find_business_data.py
Labels: Project Task

#1948 Remove queries from tests
  tests/cli/add/test_cli_add.py
  tests/cli/add/test_cli_add_family.py
  tests/cli/add/test_cli_add_relationship.py
  tests/cli/add/test_cli_add_sample.py
  tests/cli/delete/test_cli_delete_case.py
  tests/cli/get/test_cli_get_analysis.py
  tests/cli/get/test_cli_get_sample.py
  tests/cli/set/test_cli_set_case.py
  tests/cli/set/test_cli_set_flowcell.py
  tests/cli/set/test_cli_set_sample.py
  tests/meta/demultiplex/test_delete_demultiplex_api.py
  tests/meta/transfer/test_external_data.py
  tests/meta/upload/nipt/conftest.py
  tests/store/api/add/test_store_add_base.py
  tests/store/api/add/test_store_add_customer.py
  tests/store/api/find/test_find_business_data.py
  tests/store/api/status/test_store_api_status.py
  tests/store/conftest.py
Labels: Project Task

#1947 Extract application version filtering method
  cg/meta/workflow/balsamic.py
  cg/store/api/find_basic_data.py
  cg/store/api/find_business_data.py
  cg/store/filters/status_application_version_filters.py
  tests/store/filters/test_status_application_version_filters.py
Labels: Project Task

#1949 Replace Family query with existing methods
  cg/store/api/status.py
Labels: Project Task

#1952 Fix broken test
  tests/cli/test_base.py
Labels: Project Task

#1953 Fix stats model imports
  cg/apps/cgstats/crud/create.py
  cg/apps/cgstats/crud/delete.py
  cg/apps/cgstats/crud/find.py
  cg/apps/cgstats/stats.py
  tests/apps/cgstats/conftest.py
  tests/apps/cgstats/test_cgstats_create.py
  tests/apps/cgstats/test_stats.py
  tests/meta/conftest.py
  tests/meta/demultiplex/test_delete_demultiplex_api.py
  tests/meta/upload/nipt/conftest.py
Labels: Project Task

#1951 Remove unused functions in cg stats
  cg/apps/cgstats/db/models/version.py
  cg/apps/cgstats/stats.py
Labels: Project Task

#1782 Upload MIP-RNA to all DNA cases in collaborator group matching by subject_ID
  cg/meta/upload/scout/uploadscoutapi.py
  cg/store/api/find_business_data.py
  tests/store/api/find/test_find_business_data_sample.py
Labels: MIP, cg, Project Task

#1827 feat(taxprofiler): Add taxprofiler as an option to cg workflow
  alembic/versions/9008aa5065b4_add_taxprofiler_analysis_option.py
  cg/cli/workflow/base.py
  cg/cli/workflow/taxprofiler/__init__.py
  cg/cli/workflow/taxprofiler/base.py
  cg/meta/workflow/taxprofiler.py
  cg/models/taxprofiler/__init__.py
  tests/cli/workflow/taxprofiler/conftest.py
  tests/cli/workflow/taxprofiler/test_cli_taxprofiler_compound_commands.py
Labels: cg, Project Task, taxprofiler
