Repository Clinical-Genomics/cg, pull requests merged in 2023-10, with the labels that each got.

#2424 Add start_available command
  cg/cli/workflow/taxprofiler/base.py
  tests/cli/workflow/taxprofiler/test_cli_taxprofiler_compound_commands.py
  tests/conftest.py
Labels: cg, taxprofiler

#2527 Refactor flow cell SQL filter function
  cg/cli/get.py
  cg/cli/set/base.py
  cg/meta/demultiplex/delete_demultiplex_api.py
  cg/server/api.py
  cg/store/api/delete.py
  cg/store/api/find_business_data.py
  cg/store/api/status.py
  cg/store/filters/status_flow_cell_filters.py
  tests/cli/backup/test_backup_command.py
  tests/cli/get/test_cli_get_sample.py
  tests/meta/demultiplex/test_delete_demultiplex_api.py
  tests/meta/demultiplex/test_demux_post_processing.py
  tests/store/api/delete/test_store_api_delete.py
  tests/store/api/find/test_find_business_data.py
  tests/store/filters/test_status_flow_cell_filters.py
  tests/store_helpers.py
Labels: Project Task

#2526 Encrypt flow cell 2
  cg/cli/backup.py
  cg/constants/constants.py
  cg/constants/encryption.py
  cg/exc.py
  cg/meta/encryption/encryption.py
  cg/meta/encryption/sbatch.py
  cg/meta/tar/tar.py
  cg/models/cg_config.py
  cg/models/flow_cell/flow_cell.py
  cg/store/api/find_business_data.py
  tests/apps/slurm/conftest.py
  tests/cli/backup/test_backup_command.py
  tests/cli/demultiplex/test_demultiplex_flowcell.py
  tests/cli/get/test_cli_get_flow_cell.py
  tests/cli/get/test_cli_get_sample.py
  tests/cli/set/test_cli_set_flowcell.py
  tests/cli/workflow/fluffy/conftest.py
  tests/cli/workflow/mip/test_cli_mip_dna_run.py
  tests/cli/workflow/mip/test_cli_mip_rna_run.py
  tests/conftest.py
  tests/meta/clean/conftest.py
  tests/meta/demultiplex/conftest.py
  tests/meta/demultiplex/test_delete_demultiplex_api.py
  tests/meta/encryption/conftest.py
  tests/meta/encryption/test_encryption.py
  tests/store/api/conftest.py
  tests/store/api/find/test_find_business_data.py
  tests/store/api/status/test_store_api_status_cases.py
  tests/store/filters/test_status_flow_cell_filters.py
  tests/store_helpers.py
Labels: Project Task

#2590 add raredisease to constants
  cg/constants/constants.py
Labels: cg, raredisease

#2586 Add backup flow cells
  cg/cli/backup.py
  cg/exc.py
  cg/meta/backup/backup.py
  cg/meta/backup/pdc.py
  cg/models/cg_config.py
  cg/store/api/core.py
  cg/store/api/update.py
  requirements.txt
  tests/cli/backup/conftest.py
  tests/cli/backup/test_backup_command.py
  tests/conftest.py
  tests/meta/backup/test_meta_backup.py
  tests/meta/backup/test_meta_pdc.py
  tests/meta/encryption/conftest.py
  tests/store/api/test_update.py
Labels: Project Task

#2592 feat(raredisease): Add raredisease to cg workflow
  alembic/versions/11555a6fb508_add_raredisease_to_analysis_options.py
  cg/cli/workflow/base.py
  cg/cli/workflow/raredisease/__init__.py
  cg/cli/workflow/raredisease/base.py
  cg/meta/workflow/raredisease.py
  cg/models/raredisease/__init__.py
  tests/cli/workflow/raredisease/conftest.py
  tests/cli/workflow/raredisease/test_cli_raredisease_compound_commands.py
Labels: cg, raredisease
