Repository Clinical-Genomics/cg, pull requests merged in 2023-05, with the labels that each got.

#1996 add(sequencing_stats model)
  alembic/versions/ea5470295689_sequencing_stats.py
  cg/server/admin.py
  cg/server/app.py
  cg/store/models.py
Labels: Project Task

#1954 Refactor validate sample sheet
  cg/apps/demultiplex/sample_sheet/models.py
  cg/apps/demultiplex/sample_sheet/novaseq_sample_sheet.py
  cg/apps/demultiplex/sample_sheet/validate.py
  cg/cli/demultiplex/sample_sheet.py
  cg/constants/constants.py
  cg/constants/demultiplexing.py
  cg/io/validate_path.py
  cg/models/demultiplex/flow_cell.py
  tests/apps/demultiplex/test_convert_to_sample_sheet.py
  tests/apps/demultiplex/test_validate_sample_sheet.py
  tests/cli/demultiplex/test_validate_sample_sheet.py
  tests/io/test_validate_path.py
Labels: Project Task

#1997 feat(rnafusion): add qc checks
  cg/apps/tb/api.py
  cg/cli/workflow/rnafusion/base.py
  cg/constants/tb.py
  cg/exc.py
  cg/meta/workflow/analysis.py
  cg/meta/workflow/rnafusion.py
  cg/models/deliverables/metric_deliverables.py
  cg/resources/rnafusion_bundle_filenames.csv
  tests/cli/workflow/rnafusion/test_cli_rnafusion_compound_commands.py
  tests/cli/workflow/rnafusion/test_cli_rnafusion_metrics_deliver.py
  tests/cli/workflow/rnafusion/test_cli_rnafusion_store_housekeeper.py
  tests/mocks/tb_mock.py
Labels: rnafusion

#2019 Use io csv with sample sheet
  cg/apps/demultiplex/sample_sheet/create.py
  cg/apps/demultiplex/sample_sheet/models.py
  cg/apps/demultiplex/sample_sheet/novaseq_sample_sheet.py
  cg/apps/demultiplex/sample_sheet/validate.py
  cg/apps/lims/samplesheet.py
  cg/cli/demultiplex/sample_sheet.py
  cg/constants/demultiplexing.py
  cg/io/csv.py
  cg/meta/workflow/fluffy.py
  tests/apps/demultiplex/conftest.py
  tests/apps/demultiplex/test_convert_to_sample_sheet.py
  tests/apps/demultiplex/test_validate_sample_sheet.py
  tests/cli/demultiplex/test_create_sample_sheet.py
Labels: Project Task

#2042 fix(include flow cell mode S1)
  cg/apps/demultiplex/sample_sheet/models.py
  cg/apps/demultiplex/sample_sheet/validate.py
  cg/cli/demultiplex/sample_sheet.py
  cg/constants/demultiplexing.py
  cg/models/demultiplex/flow_cell.py
  tests/cli/demultiplex/test_validate_sample_sheet.py
Labels: Bug

#2041 Remove flow cell mode
  cg/apps/demultiplex/sample_sheet/models.py
  cg/apps/demultiplex/sample_sheet/novaseq_sample_sheet.py
  cg/apps/demultiplex/sample_sheet/validate.py
  cg/cli/demultiplex/sample_sheet.py
  cg/constants/demultiplexing.py
  cg/constants/sequencing.py
  cg/models/demultiplex/flow_cell.py
  cg/models/demultiplex/run_parameters.py
  tests/apps/demultiplex/test_convert_to_sample_sheet.py
  tests/apps/demultiplex/test_validate_sample_sheet.py
  tests/cli/demultiplex/test_validate_sample_sheet.py
  tests/models/demultiplexing/test_run_parameters.py
Labels: Bug, cg

#2052 feat(calculation bcl convert metrics)
  cg/apps/sequencing_metrics_parser/parsers/bcl_convert.py
  cg/apps/sequencing_metrics_parser/parsers/bcl_convert_to_sequencing_statistics.py
  cg/constants/bcl_convert_metrics.py
  cg/constants/demultiplexing.py
  tests/apps/sequencing_metrics_parser/conftest.py
  tests/apps/sequencing_metrics_parser/parsers/test_bcl_convert_to_sequencing_statistics.py
  tests/apps/sequencing_metrics_parser/parsers/test_bclconvert.py
  tests/fixtures/apps/sequencing_metrics_parser/Adapter_Metrics.csv
  tests/fixtures/apps/sequencing_metrics_parser/Demultiplex_Stats.csv
  tests/fixtures/apps/sequencing_metrics_parser/Quality_Metrics.csv
  tests/fixtures/apps/sequencing_metrics_parser/RunInfo.xml
  tests/fixtures/apps/sequencing_metrics_parser/SampleSheet.csv
Labels: Project Task

#2054 Unify models LimsFlowcellSample and NovaSeqSample
  cg/apps/cgstats/crud/create.py
  cg/apps/cgstats/crud/find.py
  cg/apps/demultiplex/sample_sheet/create.py
  cg/apps/demultiplex/sample_sheet/dummy_sample.py
  cg/apps/demultiplex/sample_sheet/index.py
  cg/apps/demultiplex/sample_sheet/models.py
  cg/apps/demultiplex/sample_sheet/novaseq_sample_sheet.py
  cg/apps/demultiplex/sample_sheet/validate.py
  cg/apps/lims/sample_sheet.py
  cg/cli/demultiplex/sample_sheet.py
  tests/apps/demultiplex/conftest.py
  tests/apps/demultiplex/test_sample_sheet.py
  tests/apps/demultiplex/test_validate_sample_sheet.py
  tests/apps/lims/conftest.py
  tests/apps/lims/test_api.py
  tests/apps/lims/test_sample_sheet.py
  tests/cli/demultiplex/test_create_sample_sheet.py
  tests/mocks/limsmock.py
Labels: cg
