Repository Clinical-Genomics/cg, pull requests merged in 2023-03, with the labels that each got.

#1773 fix(MIP-RNA) Add evaluation of exit status for upload rna-fusion
  cg/meta/upload/mip/mip_rna.py
Labels: Effort S, cg, bugfix, rna-results-in-scout

#1788 Fix/create balsamic scout config root
  cg/cli/upload/base.py
  cg/cli/upload/scout.py
  cg/meta/upload/upload_api.py
  tests/cli/upload/test_cli_scout.py
  tests/mocks/scout.py
Labels: Bug

#1787 Move filters into separate directory
  cg/store/api/findbasicdata.py
  cg/store/api/findbusinessdata.py
  cg/store/api/status.py
  cg/store/filters/status_analysis_filters.py
  cg/store/filters/status_bed_filters.py
  cg/store/filters/status_bed_version_filters.py
  cg/store/filters/status_case_filters.py
  cg/store/filters/status_case_sample_filters.py
  cg/store/filters/status_collaboration_filters.py
  cg/store/filters/status_flow_cell_filters.py
  cg/store/filters/status_sample_filters.py
  tests/store/filters/test_status_analyses_filters.py
  tests/store/filters/test_status_bed_filters.py
  tests/store/filters/test_status_bed_version_filters.py
  tests/store/filters/test_status_cases_filters.py
  tests/store/filters/test_status_collaboration_filters.py
  tests/store/filters/test_status_flow_cell_filters.py
  tests/store/filters/test_status_samples_filters.py
Labels: Project Task

#1780 Refactor customer sql
  cg/cli/add.py
  cg/cli/delete/case.py
  cg/cli/get.py
  cg/cli/set/base.py
  cg/cli/set/family.py
  cg/meta/invoice.py
  cg/meta/orders/case_submitter.py
  cg/meta/orders/fastq_submitter.py
  cg/meta/orders/metagenome_submitter.py
  cg/meta/orders/microbial_submitter.py
  cg/meta/orders/pool_submitter.py
  cg/meta/orders/sars_cov_2_submitter.py
  cg/meta/orders/submitter.py
  cg/meta/orders/ticket_handler.py
  cg/meta/transfer/external_data.py
  cg/server/api.py
  cg/server/invoices/views.py
  cg/store/api/findbasicdata.py
  cg/store/api/findbusinessdata.py
  cg/store/filters/status_customer_filters.py
  tests/cli/add/test_cli_add.py
  tests/cli/add/test_cli_add_customer.py
  tests/cli/add/test_cli_add_family.py
  tests/cli/add/test_cli_add_sample.py
  tests/cli/get/test_cli_get.py
  tests/cli/get/test_cli_get_case.py
  tests/cli/get/test_cli_get_family.py
  tests/cli/get/test_cli_get_flow_cell.py
  tests/cli/get/test_cli_get_flowcell.py
  tests/cli/get/test_cli_get_sample.py
  tests/conftest.py
  tests/meta/conftest.py
  tests/meta/orders/test_SarsCov2Submitter_store_order.py
  tests/meta/orders/test_meta_orders_api.py
  tests/meta/orders/test_meta_orders_status.py
  tests/store/api/add/test_store_add_base.py
  tests/store/api/add/test_store_add_customer.py
  tests/store/api/test_findbasicdata.py
  tests/store/conftest.py
  tests/store/test_status_customer_filters.py
  tests/store/test_store_models.py
  tests/store_helpers.py
Labels: Project Task

#1789 Refactor user sql
  cg/cli/add.py
  cg/server/admin.py
  cg/server/api.py
  cg/server/invoices/views.py
  cg/store/api/findbasicdata.py
  cg/store/user_filters.py
  tests/conftest.py
  tests/store/api/test_findbasicdata.py
  tests/store/test_user_filters.py
  tests/store_helpers.py
Labels: Project Task

#1790 Refactor organism sql
  cg/meta/orders/microbial_submitter.py
  cg/server/api.py
  cg/store/api/findbasicdata.py
  cg/store/organism_filters.py
  tests/conftest.py
  tests/meta/orders/test_meta_orders_status.py
  tests/store/api/test_findbasicdata.py
  tests/store/test_organism_filters.py
Labels: Project Task

#1769 Add file tags to protect in Housekeeper for Balsamic analysis
  cg/constants/housekeeper_tags.py
Labels: Balsamic, Gain S, Effort S, Urgency S, Project Task

#1784 Move queries into BaseHandler
  cg/models/cg_config.py
  cg/store/api/base.py
  cg/store/api/core.py
  cg/store/api/findbasicdata.py
  cg/store/api/findbusinessdata.py
  cg/store/api/status.py
  cg/store/filters/status_collaboration_filters.py
  tests/cli/add/test_cli_add_customer.py
  tests/cli/test_base.py
  tests/store/api/add/test_store_add_customer.py
  tests/store/api/test_base.py
  tests/store/api/test_findbasicdata.py
  tests/store/api/test_findbusinessdata.py
  tests/store/api/test_store_api_status_analysis.py
  tests/store/filters/test_status_application_filters.py
  tests/store/filters/test_status_bed_filters.py
  tests/store/filters/test_status_bed_version_filters.py
  tests/store/filters/test_status_cases_filters.py
  tests/store/filters/test_status_collaboration_filters.py
  tests/store/filters/test_status_flow_cell_filters.py
  tests/store/filters/test_status_invoice_filters.py
  tests/store/filters/test_status_pool_filters.py
  tests/store/filters/test_status_samples_filters.py
  tests/store/test_organism_filters.py
  tests/store/test_status_customer_filters.py
  tests/store/test_user_filters.py
Labels: Project Task

#1798 refactor(application model refinement)
  cg/cli/add.py
  cg/constants/constants.py
  cg/meta/report/mip_dna.py
  cg/meta/report/report_api.py
  cg/meta/upload/vogue.py
  cg/server/api.py
  cg/store/api/core.py
  cg/store/api/find_basic_data.py
  cg/store/api/find_business_data.py
  cg/store/api/import_func.py
  cg/store/filters/status_application_filters.py
  tests/cli/workflow/mip/conftest.py
  tests/conftest.py
  tests/meta/conftest.py
  tests/meta/orders/test_meta_orders_status.py
  tests/meta/upload/vogue/conftest.py
  tests/meta/upload/vogue/test_upload_vogue.py
  tests/meta/workflow/conftest.py
  tests/store/api/add/test_store_add_base.py
  tests/store/api/conftest.py
  tests/store/api/test_find_basic_data.py
  tests/store/api/test_find_business_data.py
  tests/store/api/test_store_import_func.py
  tests/store/conftest.py
  tests/store/filters/test_status_application_filters.py
  tests/store_helpers.py
Labels: Project Task

#1797 Rnafusion: add tower support
  cg/cli/workflow/nextflow/options.py
  cg/cli/workflow/rnafusion/base.py
  cg/cli/workflow/tower/__init__.py
  cg/cli/workflow/tower/options.py
  cg/constants/constants.py
  cg/meta/workflow/analysis.py
  cg/meta/workflow/balsamic.py
  cg/meta/workflow/nextflow_common.py
  cg/meta/workflow/rnafusion.py
  cg/meta/workflow/tower_common.py
  cg/models/cg_config.py
  cg/utils/utils.py
  tests/cli/workflow/rnafusion/test_cli_rnafusion_run.py
  tests/conftest.py
Labels: rnafusion

#1803 (Delivery) Handle error when hard link for file already exists
  cg/exc.py
  cg/meta/deliver.py
Labels: Bug

#1800 refactor(refine pool refactoring)
  cg/server/api.py
  cg/store/api/find_business_data.py
  cg/store/filters/status_pool_filters.py
  cg/utils/dict.py
  tests/meta/orders/test_meta_orders_status.py
  tests/store/api/conftest.py
  tests/store/api/test_find_business_data.py
  tests/store/conftest.py
  tests/store/filters/test_status_pool_filters.py
  tests/store_helpers.py
Labels: Project Task

#1810 refine_refactor_invoice
  cg/server/invoices/views.py
  cg/store/api/find_business_data.py
  cg/store/filters/status_invoice_filters.py
  tests/store/api/test_find_business_data.py
  tests/store/filters/test_status_invoice_filters.py
  tests/store_helpers.py
Labels: Project Task

#1813 Move filter scripts to filter folder
  cg/store/api/find_basic_data.py
  cg/store/filters/status_organism_filters.py
  cg/store/filters/status_user_filters.py
  tests/store/test_organism_filters.py
  tests/store/test_user_filters.py
Labels: Project Task

#1793 Refactor set case command
  cg/cli/set/family.py
  cg/store/api/find_basic_data.py
Labels: Enhancement

#1792 Add filters for panel
  cg/cli/add.py
  cg/cli/set/families.py
  cg/cli/set/family.py
  cg/server/api.py
  cg/store/api/find_basic_data.py
  cg/store/filters/status_panel_filters.py
  tests/conftest.py
  tests/store/test_panel_filters.py
  tests/store_helpers.py
Labels: Project Task

#1818 RNAfusion: Change launch dir to case dir
  cg/meta/workflow/rnafusion.py
Labels: rnafusion

#1815 refactor(server/api.py function names)
  cg/server/api.py
Labels: Project Task

#1814 Rnafusion move head job to slurm
  cg/constants/nextflow.py
  cg/meta/workflow/nextflow_common.py
  cg/meta/workflow/rnafusion.py
  cg/utils/commands.py
Labels: rnafusion

#1829 Fix typo causing removal of failed flow cells to fail
  cg/meta/clean/demultiplexed_flow_cells.py
Labels: Bug

#1833 refactor(serrver/api variables)
  cg/server/api.py
Labels: Project Task

#1834 refactor(get_all_samples function names)
  cg/cli/status.py
  cg/meta/deliver_ticket.py
  cg/meta/transfer/lims.py
  cg/server/api.py
  cg/store/api/find_business_data.py
  cg/store/api/status.py
  tests/meta/deliver/test_deliver_ticket.py
  tests/meta/orders/test_meta_orders_api.py
  tests/meta/orders/test_meta_orders_status.py
  tests/meta/transfer/test_meta_transfer_flowcell.py
  tests/meta/transfer/test_meta_transfer_lims.py
  tests/store/api/test_find_business_data.py
  tests/store/api/test_store_api_status.py
  tests/store/conftest.py
  tests/store/test_delivery.py
Labels: Project Task

#1835 refactor(sample add filters and tests)
  cg/store/filters/status_sample_filters.py
  tests/store/filters/test_status_samples_filters.py
Labels: Project Task

#1839 fix(bug in trailblazer api)
  cg/server/api.py
Labels: Project Task

#1838 refactor(function active_sample)
  cg/meta/demultiplex/delete_demultiplex_api.py
  cg/store/api/find_business_data.py
  tests/meta/demultiplex/test_delete_demultiplex_api.py
  tests/store/api/conftest.py
  tests/store/api/find/test_find_business_data.py
  tests/store/api/find/test_find_business_data_sample.py
Labels: Project Task

#1843 refactor(get_pools_- and get_samples_to_invoice)
  cg/constants/invoice.py
  cg/server/invoices/views.py
  cg/store/api/status.py
  cg/store/filters/status_pool_filters.py
  tests/store/api/conftest.py
  tests/store/api/status/test_store_api_status_customer.py
  tests/store/api/status/test_store_api_status_pool.py
  tests/store/api/status/test_store_api_status_sample.py
Labels: Project Task

#1852 add new function to get samples by list of customer IDs
  cg/store/api/find_business_data.py
  tests/store/api/conftest.py
  tests/store/api/find/test_find_business_data_sample.py
Labels: cg

#1849 refactor(add analysis filters and tests)
  cg/store/filters/status_analysis_filters.py
  tests/store/conftest.py
  tests/store/filters/test_status_analyses_filters.py
  tests/store_helpers.py
Labels: Project Task

#1845 refactor(get_samples_by_subject_id)
  cg/meta/orders/case_submitter.py
  cg/meta/upload/scout/uploadscoutapi.py
  cg/server/api.py
  cg/store/api/find_basic_data.py
  cg/store/api/find_business_data.py
  cg/store/filters/status_customer_filters.py
  cg/store/filters/status_sample_filters.py
  tests/store/api/conftest.py
  tests/store/api/find/test_find_business_data_sample.py
  tests/store/filters/test_status_customer_filters.py
  tests/store/filters/test_status_samples_filters.py
Labels: Project Task

#1858 Refactor find family
  cg/meta/orders/case_submitter.py
  cg/meta/orders/fastq_submitter.py
  cg/meta/orders/metagenome_submitter.py
  cg/meta/orders/microbial_submitter.py
  cg/meta/orders/pool_submitter.py
  cg/meta/workflow/microsalt.py
  cg/store/api/find_business_data.py
  cg/store/filters/status_case_filters.py
  tests/cli/workflow/conftest.py
  tests/meta/orders/test_meta_orders_api.py
  tests/store/api/find/test_find_business_data.py
  tests/store_helpers.py
Labels: Project Task

#1854 Extract filtering cases on ticket
  cg/cli/deliver/base.py
  cg/meta/deliver_ticket.py
  cg/meta/rsync/rsync_api.py
  cg/store/api/find_business_data.py
  cg/store/filters/status_case_filters.py
  tests/apps/cgstats/conftest.py
  tests/cli/add/test_cli_add_family.py
  tests/cli/delete/test_cases.py
  tests/cli/deliver/conftest.py
  tests/cli/deliver/test_deliver_base.py
  tests/cli/deliver/test_run_deliver_cmd.py
  tests/cli/set/test_families.py
  tests/cli/store/test_fastq.py
  tests/cli/workflow/conftest.py
  tests/cli/workflow/microsalt/test_microsalt_case_config.py
  tests/cli/workflow/microsalt/test_microsalt_run.py
  tests/conftest.py
  tests/meta/deliver/conftest.py
  tests/meta/deliver/test_deliver_ticket.py
  tests/meta/orders/test_meta_orders_api.py
  tests/meta/orders/test_meta_orders_status.py
  tests/meta/orders/test_ticket_handler.py
  tests/meta/rsync/conftest.py
  tests/meta/rsync/test_rsync.py
  tests/meta/transfer/conftest.py
  tests/meta/transfer/test_external_data.py
  tests/mocks/osticket.py
  tests/store/api/conftest.py
  tests/store/api/find/test_find_business_data.py
  tests/store/filters/test_status_cases_filters.py
Labels: Project Task

#1846 refactor(remove analyses function)
  cg/store/api/find_business_data.py
  cg/store/filters/status_analysis_filters.py
  tests/cli/workflow/fastq/test_fastq_base.py
  tests/store/api/find/test_find_business_data_analysis.py
  tests/store/api/status/test_store_api_status_cases.py
  tests/store/conftest.py
  tests/store/filters/test_status_analyses_filters.py
Labels: Project Task

#1853 Refactor filtering of running cases
  cg/meta/workflow/analysis.py
  cg/store/api/find_business_data.py
  cg/store/api/status.py
  cg/store/filters/status_case_filters.py
  tests/conftest.py
  tests/store/filters/test_status_cases_filters.py
Labels: Project Task

#1826 Refactor application version filtering
  cg/store/api/find_basic_data.py
  cg/store/filters/status_application_version_filters.py
  tests/conftest.py
  tests/store/api/find/test_find_basic_data.py
  tests/store/conftest.py
  tests/store/filters/test_status_application_version_filters.py
  tests/store/test_store_models.py
  tests/store_helpers.py
Labels: Project Task

#1864 refactor(function analysis)
  cg/cli/generate/report/utils.py
  cg/meta/report/report_api.py
  cg/store/api/find_business_data.py
  cg/store/filters/status_analysis_filters.py
  tests/store/api/find/test_find_business_data.py
  tests/store/filters/test_status_analyses_filters.py
Labels: Project Task

#1847 Remove dead case filter functions
  cg/meta/workflow/balsamic.py
Labels: Project Task

#1867 refactor(move queries to findhandler)
  cg/cli/workflow/microsalt/base.py
  cg/meta/upload/nipt/nipt.py
  cg/store/api/find_business_data.py
  tests/store/api/conftest.py
  tests/store/api/find/test_find_business_data_analysis.py
Labels: Project Task

#1871 Rename function get_customer_by_customer_id
  cg/cli/add.py
  cg/cli/get.py
  cg/cli/set/base.py
  cg/cli/set/family.py
  cg/constants/invoice.py
  cg/meta/invoice.py
  cg/meta/orders/case_submitter.py
  cg/meta/orders/fastq_submitter.py
  cg/meta/orders/metagenome_submitter.py
  cg/meta/orders/microbial_submitter.py
  cg/meta/orders/pool_submitter.py
  cg/meta/orders/sars_cov_2_submitter.py
  cg/meta/orders/ticket_handler.py
  cg/meta/transfer/external_data.py
  cg/server/api.py
  cg/server/invoices/views.py
  cg/store/api/find_basic_data.py
  cg/store/api/status.py
  tests/cli/add/test_cli_add_customer.py
  tests/meta/orders/test_SarsCov2Submitter_store_order.py
  tests/meta/orders/test_meta_orders_api.py
  tests/store/api/add/test_store_add_customer.py
  tests/store/api/find/test_find_basic_data.py
  tests/store/api/find/test_find_business_data_sample.py
  tests/store/api/status/test_store_api_status_customer.py
  tests/store/api/status/test_store_api_status_pool.py
  tests/store/api/status/test_store_api_status_sample.py
  tests/store/conftest.py
  tests/store/test_store_models.py
  tests/store_helpers.py
Labels: Project Task

#1860 Refactor families
  cg/cli/get.py
  cg/cli/status.py
  cg/server/api.py
  cg/store/api/find_business_data.py
  cg/store/filters/status_case_filters.py
  tests/cli/compress/test_cli_compress_fastq.py
  tests/conftest.py
  tests/meta/orders/test_PoolSubmitter_validate_order.py
  tests/meta/orders/test_meta_orders_status.py
  tests/meta/report/conftest.py
  tests/meta/upload/scout/conftest.py
  tests/meta/upload/scout/test_meta_upload_scoutapi_rna.py
  tests/store/api/delete/test_store_api_delete.py
  tests/store/api/find/test_find_business_data_case.py
  tests/store/api/status/test_store_api_status_cases.py
  tests/store/conftest.py
  tests/store/filters/test_status_cases_filters.py
  tests/store_helpers.py
Labels: Project Task
