Repository Clinical-Genomics/cg, pull requests merged in 2023-11, with the labels that each got.

#2648 feat(tb): Remove unused function
  cg/apps/tb/api.py
Labels: Project Task

#2690 Count dsmc processes
  cg/meta/backup/pdc.py
  tests/cli/backup/test_backup_command.py
Labels: Project Task

#2694 feat(encrypt_dir): Add and change current
  cg/cli/backup.py
  cg/meta/backup/backup.py
  cg/meta/backup/pdc.py
  cg/models/cg_config.py
  tests/cli/backup/conftest.py
  tests/cli/backup/test_backup_command.py
  tests/conftest.py
  tests/meta/backup/conftest.py
  tests/meta/backup/test_meta_backup.py
Labels: Project Task

#2501 RNAFUSION: update filenames for 2.4.0
  cg/resources/rnafusion_bundle_filenames.csv
Labels: rnafusion

#2703 Add cg nas and encryption dir
  cg/cli/clean.py
  cg/models/cg_config.py
  tests/conftest.py
Labels: Project Task

#2707 feat(encrypt): Answer yes in gpg encrypt and decrypt cmds
  cg/constants/encryption.py
  cg/meta/encryption/encryption.py
  tests/meta/encryption/conftest.py
Labels: Bug

#2720 fix - catch sample sheet errors in sample sheet generation automation
  cg/cli/demultiplex/sample_sheet.py
Labels: Bug, demultiplex
