Repository Clinical-Genomics/cg, pull requests merged in 2023-06, with the labels that each got.

#1998 feat(taxprofiler): Add config case
  cg/cli/workflow/taxprofiler/base.py
  cg/cli/workflow/taxprofiler/options.py
  cg/constants/sequencing.py
  cg/constants/taxprofiler.py
  cg/meta/workflow/fastq.py
  cg/meta/workflow/nextflow_common.py
  cg/meta/workflow/taxprofiler.py
  cg/models/cg_config.py
  cg/models/taxprofiler/taxprofiler_sample.py
  tests/cli/workflow/taxprofiler/conftest.py
  tests/cli/workflow/taxprofiler/test_cli_taxprofiler_config_case.py
  tests/conftest.py
Labels: cg, Project Task, taxprofiler

#2088 Organise demux tests
  cg/models/demultiplex/flow_cell.py
  tests/cli/compress/test_store_fastq.py
  tests/cli/demultiplex/conftest.py
  tests/cli/demultiplex/test_demultiplex_flowcell.py
  tests/conftest.py
  tests/fixtures/DEMUX/160219_D00410_0217_AHJKMYBCXX/Unaligned5/Project_337334/Sample_ADM1136A3_XTC08/ADM1136A3_XTC08_AGTGGTCA_L001_R1_001.fastq.gz
  tests/fixtures/DEMUX/160219_D00410_0217_AHJKMYBCXX/Unaligned5/Project_337334/Sample_ADM1136A3_XTC08/ADM1136A3_XTC08_AGTGGTCA_L001_R2_001.fastq.gz
  tests/fixtures/DEMUX/160219_D00410_0217_AHJKMYBCXX/Unaligned5/Project_337334/Sample_ADM1136A3_XTC08/ADM1136A3_XTC08_AGTGGTCA_L002_R1_001.fastq.gz
  tests/fixtures/DEMUX/160219_D00410_0217_AHJKMYBCXX/Unaligned5/Project_337334/Sample_ADM1136A3_XTC08/ADM1136A3_XTC08_AGTGGTCA_L002_R2_001.fastq.gz
  tests/fixtures/DEMUX/160219_D00410_0217_AHJKMYBCXX/runParameters.xml
  tests/fixtures/apps/demultiplexing/201203_A00689_0200_AHVKJCDRXX/SampleSheet.csv
  tests/fixtures/apps/demultiplexing/SampleSheetS2_Bcl2Fastq.csv
  tests/fixtures/apps/demultiplexing/SampleSheetS2_Dragen.csv
  tests/fixtures/apps/demultiplexing/flow-cell-runs/201203_A00689_0200_AHVKJCDRXX/RunParameters.xml
  tests/fixtures/apps/demultiplexing/flow-cell-runs/201203_A00689_0200_AHVKJCDRXX/SampleSheet.csv
  tests/fixtures/apps/demultiplexing/flow-cell-runs/hiseq/180522_ST-E00198_0301_BHLCKNCCXY/RTAComplete.txt
  tests/fixtures/apps/demultiplexing/flow-cell-runs/hiseq/180522_ST-E00198_0301_BHLCKNCCXY/SampleSheet.csv
  tests/fixtures/apps/demultiplexing/flow-cell-runs/hiseq/180522_ST-E00198_0301_BHLCKNCCXY/copy_complete.txt
  tests/fixtures/apps/demultiplexing/flow-cell-runs/hiseq/180522_ST-E00198_0301_BHLCKNCCXY/runParameters.xml
  tests/fixtures/apps/demultiplexing/flow-cell-runs/nova_seq_6000/201203_A00689_0200_AHVKJCDRXX/CopyComplete.txt
  tests/fixtures/apps/demultiplexing/flow-cell-runs/nova_seq_6000/201203_A00689_0200_AHVKJCDRXX/HVKJCDRXX_demultiplex.stderr
  tests/fixtures/apps/demultiplexing/flow-cell-runs/nova_seq_6000/201203_A00689_0200_AHVKJCDRXX/RTAComplete.txt
  tests/fixtures/apps/demultiplexing/flow-cell-runs/nova_seq_6000/201203_A00689_0200_AHVKJCDRXX/RunParameters.xml
  tests/fixtures/apps/demultiplexing/flow-cell-runs/nova_seq_6000/201203_A00689_0200_AHVKJCDRXX/SampleSheet.csv
  tests/fixtures/apps/demultiplexing/flow-cell-runs/nova_seq_6000/201203_A00689_0200_AHVKJCDRXX/demuxstarted.txt
  tests/fixtures/apps/demultiplexing/flow-cell-runs/nova_seq_6000/211101_A00187_0615_AHLG5GDRXY/CopyComplete.txt
  tests/fixtures/apps/demultiplexing/flow-cell-runs/nova_seq_6000/211101_A00187_0615_AHLG5GDRXY/HLG5GDRXY_demultiplex.stderr
  tests/fixtures/apps/demultiplexing/flow-cell-runs/nova_seq_6000/211101_A00187_0615_AHLG5GDRXY/HLG5GDRXY_demultiplex.stdout
  tests/fixtures/apps/demultiplexing/flow-cell-runs/nova_seq_6000/211101_A00187_0615_AHLG5GDRXY/RTAComplete.txt
  tests/fixtures/apps/demultiplexing/flow-cell-runs/nova_seq_6000/211101_A00187_0615_AHLG5GDRXY/RunParameters.xml
  tests/fixtures/apps/demultiplexing/flow-cell-runs/nova_seq_6000/211101_A00187_0615_AHLG5GDRXY/SampleSheet.csv
  tests/fixtures/apps/demultiplexing/flow-cell-runs/nova_seq_6000/211101_A00187_0615_AHLG5GDRXY/demuxstarted.txt
  tests/fixtures/apps/demultiplexing/flow-cell-runs/nova_seq_x/20230508_LH00188_0003_A22522YLT3/RunParameters.xml
  tests/fixtures/apps/demultiplexing/hiseq_run/201203_A00689_0200_AHVKJCDRXX/HVKJCDRXX_demultiplex.stderr
  tests/fixtures/apps/demultiplexing/hiseq_run/201203_A00689_0200_AHVKJCDRXX/RunParameters.xml
  tests/fixtures/apps/demultiplexing/hiseq_run/201203_A00689_0200_AHVKJCDRXX/SampleSheet.csv
  tests/fixtures/apps/demultiplexing/hiseq_run/201203_A00689_0200_AHVKJCDRXX/demuxstarted.txt
  tests/fixtures/apps/demultiplexing/hiseq_run/runParameters.xml
  tests/fixtures/apps/demultiplexing/run_parameters/RunParameters_different_index_cycles.xml
  tests/fixtures/apps/demultiplexing/run_parameters/runParameters_missing_flowcell_run_field.xml
  tests/fixtures/apps/demultiplexing/unknown_run_parameters.xml
  tests/meta/clean/conftest.py
  tests/meta/clean/test_clean_demultiplexed_runs.py
  tests/meta/conftest.py
  tests/meta/transfer/test_meta_transfer_flowcell.py
  tests/store/api/conftest.py
  tests/store/api/find/test_find_business_data.py
Labels: cg

#2099 fix(column type sequencing metrics)
  alembic/versions/a34039f530c5_alter_column_types_sample_lane_.py
  cg/store/models.py
Labels: Project Task

#2102 Fix fluffy test
  tests/cli/workflow/fluffy/test_cli_create_samplesheet.py
  tests/cli/workflow/fluffy/test_cli_link.py
Labels: Bug

#2103 Refactor case filters
  cg/store/api/base.py
  cg/store/api/find_business_data.py
  cg/store/api/status.py
  cg/store/filters/status_case_filters.py
  tests/store/filters/test_status_cases_filters.py
Labels: Project Task

#2112 Refactor demultiplex and sample sheet constants
  cg/apps/demultiplex/sample_sheet/dummy_sample.py
  cg/apps/demultiplex/sample_sheet/models.py
  cg/apps/demultiplex/sample_sheet/novaseq_sample_sheet.py
  cg/apps/demultiplex/sample_sheet/validate.py
  cg/apps/sequencing_metrics_parser/models/bcl_convert.py
  cg/apps/sequencing_metrics_parser/parsers/bcl_convert.py
  cg/constants/demultiplexing.py
  cg/constants/sequencing.py
  cg/meta/workflow/fluffy.py
  cg/models/demultiplex/flow_cell.py
  tests/apps/demultiplex/conftest.py
  tests/apps/demultiplex/test_convert_to_sample_sheet.py
  tests/apps/sequencing_metrics_parser/conftest.py
  tests/conftest.py
Labels: cg

#2124 feat(snapshottest): Remove
  CONTRIBUTING.md
  requirements-dev.txt
  tests/cli/workflow/microsalt/snapshots/__init__.py
  tests/cli/workflow/microsalt/snapshots/snap_test_microsalt_case_config.py
Labels: Refactor

#2125 feat(docutils): Remove
  requirements-dev.txt
Labels: Refactor

#2127 feat(pytest): Unfreeze
  requirements-dev.txt
Labels: Refactor

#2129 feat(ruff): Add
  .pre-commit-config.yaml
  pyproject.toml
  requirements-dev.txt
Labels: Enhancement

#2133 fix(rnafusion): mapped reads percentage calculation (patch)
  cg/meta/report/rnafusion.py
  tests/meta/report/conftest.py
Labels: rnafusion

#2122 feat(refactor): Remove unnecessary function in Analysis API
  cg/meta/workflow/analysis.py
  cg/meta/workflow/fluffy.py
  cg/meta/workflow/microsalt.py
  cg/meta/workflow/mutant.py
  cg/store/api/find_business_data.py
  tests/store/api/find/test_find_business_data_case.py
Labels: Refactor

#2192 add(temporary column sample table)
  alembic/versions/ffb9f8ab8e62_add_temp_read_col.py
  cg/meta/demultiplex/demux_post_processing.py
  cg/store/models.py
  tests/meta/demultiplex/test_demux_post_processing.py
Labels: Project Task

#2198 add(flow cell and sample links to sample lane seq metrics)
  cg/server/admin.py
Labels: Project Task

#2200 fix(import type hint model)
  cg/meta/transfer/external_data.py
Labels: Project Task
