Repository Clinical-Genomics/cg, pull requests merged in 2023-09, with the labels that each got.

#2406 Migrate nipt models
  cg/meta/upload/nipt/models.py
  tests/meta/upload/nipt/test_models.py
Labels: Project Task

#2404 Migrate slurm model
  cg/models/slurm/sbatch.py
Labels: Project Task

#2394 Migrate sample sheet models
  cg/apps/demultiplex/sample_sheet/models.py
  cg/apps/demultiplex/sample_sheet/read_sample_sheet.py
  cg/cli/demultiplex/sample_sheet.py
  cg/models/demultiplex/flow_cell.py
Labels: Project Task

#2390 Migrate SampleData model
  cg/apps/demultiplex/demux_report.py
Labels: Project Task

#2405 Migrate mutant sample config model
  cg/models/workflow/mutant.py
  cg/models/workflow/validators.py
Labels: Project Task

#2357 Add tower to cg workflow taxprofiler run
  cg/cli/workflow/taxprofiler/base.py
  cg/cli/workflow/taxprofiler/taxprofiler_command.py
  cg/meta/workflow/taxprofiler.py
  cg/models/cg_config.py
  tests/cli/workflow/taxprofiler/test_cli_taxprofiler_run.py
  tests/conftest.py
Labels: cg, taxprofiler

#2398 Migrate scout models
  cg/models/scout/scout_load_config.py
  cg/models/scout/validators.py
  tests/apps/scout/conftest.py
  tests/apps/scout/test_scout_load_config.py
Labels: Project Task

#2401 Check if fastq files exist for a sample before adding
  cg/meta/demultiplex/demux_post_processing.py
  cg/meta/demultiplex/utils.py
  cg/meta/demultiplex/validation.py
  tests/conftest.py
  tests/meta/demultiplex/test_demux_post_processing.py
  tests/meta/demultiplex/test_status_db_storage_functions.py
  tests/meta/demultiplex/test_utils.py
  tests/meta/demultiplex/test_validation.py
Labels: Project Task

#2403 feat(NovaSeq X) Parse manifest file to ensure sync
  cg/cli/demultiplex/base.py
  cg/cli/demultiplex/demux.py
  cg/constants/demultiplexing.py
  cg/meta/demultiplex/utils.py
  tests/conftest.py
  tests/fixtures/apps/demultiplexing/flow_cells/20230508_LH00188_0003_A22522YLT3/Manifest.tsv
  tests/meta/demultiplex/conftest.py
  tests/meta/demultiplex/test_utils.py
Labels: Project Task

#2365 Added expected header structure in sample sheet validation
  cg/cli/demultiplex/demux.py
  cg/constants/bcl_convert_metrics.py
  cg/models/demultiplex/flow_cell.py
  tests/cli/demultiplex/test_create_sample_sheet.py
  tests/conftest.py
  tests/fixtures/apps/demultiplexing/flow_cells/201203_A00689_0200_AHVKJCDRXY/HVKJCDRXX_demultiplex.stderr
  tests/fixtures/apps/demultiplexing/flow_cells/201203_A00689_0200_AHVKJCDRXY/HVKJCDRXX_demultiplex.stdout
  tests/fixtures/apps/demultiplexing/flow_cells/201203_A00689_0200_AHVKJCDRXY/RTAComplete.txt
  tests/fixtures/apps/demultiplexing/flow_cells/201203_A00689_0200_AHVKJCDRXY/RunParameters.xml
  tests/fixtures/apps/demultiplexing/flow_cells/201203_A00689_0200_AHVKJCDRXY/SampleSheet.csv
  tests/fixtures/apps/demultiplexing/flow_cells/201203_A00689_0200_AHVKJCDRXY/copycomplete.txt
  tests/fixtures/apps/demultiplexing/flow_cells/201203_A00689_0200_AHVKJCDRXY/demuxstarted.txt
Labels: Enhancement

#2455 delete(TransferFlowcell class)
  cg/cli/transfer.py
  cg/meta/transfer/__init__.py
  cg/meta/transfer/flowcell.py
  tests/meta/conftest.py
  tests/meta/transfer/test_meta_transfer_flowcell.py
Labels: Project Task

#2461 delete(cgstats)
  CONTRIBUTING.md
  cg/apps/cgstats/__init__.py
  cg/apps/cgstats/crud/__init__.py
  cg/apps/cgstats/crud/create.py
  cg/apps/cgstats/crud/delete.py
  cg/apps/cgstats/crud/find.py
  cg/apps/cgstats/db/__init__.py
  cg/apps/cgstats/db/models/__init__.py
  cg/apps/cgstats/db/models/base.py
  cg/apps/cgstats/db/models/datasource.py
  cg/apps/cgstats/db/models/demux.py
  cg/apps/cgstats/db/models/demux_sample.py
  cg/apps/cgstats/db/models/dragen_demux_sample.py
  cg/apps/cgstats/db/models/flowcell.py
  cg/apps/cgstats/db/models/project.py
  cg/apps/cgstats/db/models/sample.py
  cg/apps/cgstats/db/models/support_params.py
  cg/apps/cgstats/db/models/unaligned.py
  cg/apps/cgstats/db/models/version.py
  cg/apps/cgstats/parsers/__init__.py
  cg/apps/cgstats/parsers/adapter_metrics.py
  cg/apps/cgstats/parsers/conversion_stats.py
  cg/apps/cgstats/parsers/demux_stats.py
  cg/apps/cgstats/parsers/dragen_demultiplexing_stats.py
  cg/apps/cgstats/parsers/quality_metrics.py
  cg/apps/cgstats/parsers/run_info.py
  cg/apps/cgstats/stats.py
  cg/apps/demultiplex/demux_report.py
  cg/cli/demultiplex/base.py
  cg/cli/demultiplex/report.py
  cg/models/cg_config.py
  cg/models/cgstats/__init__.py
  cg/models/cgstats/flowcell.py
  cg/models/cgstats/stats_sample.py
  cg/models/demultiplex/demux_results.py
  documentation/README.md
  templates/config.yaml
  tests/apps/cgstats/conftest.py
  tests/apps/cgstats/crud/test_create_novaseq.py
  tests/apps/cgstats/crud/test_delete.py
  tests/apps/cgstats/parsers/test_adapter_metrics.py
  tests/apps/cgstats/parsers/test_conversion_stats.py
  tests/apps/cgstats/parsers/test_demux_stats.py
  tests/apps/cgstats/parsers/test_quality_metrics.py
  tests/apps/cgstats/parsers/test_run_info.py
  tests/apps/cgstats/test_cgstats_create.py
  tests/apps/cgstats/test_stats.py
  tests/conftest.py
  tests/meta/conftest.py
  tests/meta/demultiplex/conftest.py
  tests/meta/demultiplex/test_delete_demultiplex_api.py
  tests/meta/transfer/conftest.py
  tests/meta/upload/nipt/conftest.py
  tests/models/demultiplexing/conftest.py
  tests/models/demultiplexing/test_demux_results.py
Labels: Project Task

#2478 feat(isort): Add
  .pre-commit-config.yaml
  pyproject.toml
Labels: Enhancement

#2481 feat(ruff): Update
  .pre-commit-config.yaml
Labels: Enhancement

#2517 feat(encryption)
  cg/cli/backup.py
  cg/meta/backup/backup.py
  cg/meta/backup/pdc.py
  cg/models/cg_config.py
  tests/cli/backup/conftest.py
  tests/conftest.py
  tests/meta/backup/conftest.py
  tests/meta/backup/test_meta_backup.py
Labels: Project Task

#2512 feat(dragen): Use cg-dragen2
  cg/apps/slurm/sbatch.py
Labels: Enhancement
