Repository Clinical-Genomics/cg, pull requests merged in 2024-02, with the labels that each got.

#2911 feat(hermes): refactor to workflow in CLI call
  cg/apps/hermes/hermes_api.py
Labels: Enhancement

#2917 Use workflow instead of order_type
  cg/store/crud/create.py
Labels: Bug

#2925 Fix: Dry run for Balsamic run analysis
  cg/cli/workflow/balsamic/base.py
  cg/meta/workflow/analysis.py
  tests/cli/workflow/balsamic/test_run.py
Labels: Bug

#2934 Remove adapter columns from Illumina samplesheet
  cg/apps/demultiplex/sample_sheet/read_sample_sheet.py
  cg/apps/demultiplex/sample_sheet/sample_models.py
  cg/constants/demultiplexing.py
  tests/fixtures/apps/demultiplexing/flow_cells/170517_ST-E00266_0210_BHJCFFALXX/SampleSheet_bcl_convert.csv
  tests/fixtures/apps/demultiplexing/flow_cells/180508_ST-E00269_0269_AHL32LCCXY/SampleSheet_bcl_convert.csv
  tests/fixtures/apps/demultiplexing/flow_cells/181005_D00410_0735_BHM2LNBCX2/SampleSheet_dragen.csv
  tests/fixtures/apps/demultiplexing/flow_cells/190927_A00689_0069_BHLYWYDSXX/CorrectSampleSheet.csv
  tests/fixtures/apps/demultiplexing/flow_cells/20231108_LH00188_0028_B22F52TLT3/CorrectSampleSheet.csv
  tests/fixtures/apps/demultiplexing/flow_cells/230912_A00187_1009_AHK33MDRX3/CorrectSampleSheet.csv
Labels: demultiplex

#2932 Refactor to workflow tb api
  cg/apps/demultiplex/demultiplex_api.py
  cg/apps/tb/api.py
  cg/apps/tb/models.py
  cg/cli/upload/clinical_delivery.py
  cg/cli/workflow/fastq/fastq_service.py
  cg/meta/rsync/rsync_api.py
  cg/meta/workflow/analysis.py
Labels: Enhancement

#2958 feat - new sample sheet validation and API
  cg/apps/demultiplex/sample_sheet/api.py
  cg/apps/demultiplex/sample_sheet/create.py
  cg/apps/demultiplex/sample_sheet/override_cycles_validator.py
  cg/apps/demultiplex/sample_sheet/read_sample_sheet.py
  cg/apps/demultiplex/sample_sheet/sample_sheet_creator.py
  cg/apps/demultiplex/sample_sheet/sample_sheet_validator.py
  cg/cli/demultiplex/demux.py
  cg/cli/demultiplex/sample_sheet.py
  cg/constants/bcl_convert_metrics.py
  cg/constants/demultiplexing.py
  cg/exc.py
  cg/meta/demultiplex/housekeeper_storage_functions.py
  cg/meta/demultiplex/utils.py
  cg/meta/workflow/fluffy.py
  cg/models/cg_config.py
  cg/models/flow_cell/flow_cell.py
  cg/utils/files.py
  tests/apps/demultiplex/conftest.py
  tests/apps/demultiplex/test_demultiplex_api.py
  tests/apps/demultiplex/test_override_cycles_validator.py
  tests/apps/demultiplex/test_read_sample_sheet.py
  tests/apps/demultiplex/test_sample_models.py
  tests/apps/demultiplex/test_sample_sheet_creator.py
  tests/apps/demultiplex/test_sample_sheet_creator_factory.py
  tests/apps/demultiplex/test_sample_sheet_models.py
  tests/apps/demultiplex/test_sample_sheet_validator.py
  tests/cli/demultiplex/test_create_sample_sheet.py
  tests/cli/demultiplex/test_demultiplex_flowcell.py
  tests/cli/demultiplex/test_validate_sample_sheet.py
  tests/cli/workflow/fluffy/test_cli_create_samplesheet.py
  tests/conftest.py
  tests/fixture_plugins/demultiplex_fixtures/name_fixtures.py
  tests/fixture_plugins/demultiplex_fixtures/path_fixtures.py
  tests/fixture_plugins/demultiplex_fixtures/sample_sheet_fixtures.py
  tests/fixtures/apps/demultiplexing/demultiplexed-runs/20230508_LH00188_0003_A22522YLT3/SampleSheet.csv
  tests/fixtures/apps/demultiplexing/demultiplexed-runs/230504_A00689_0804_BHY7FFDRX2/SampleSheet.csv
  tests/fixtures/apps/demultiplexing/demultiplexed-runs/230505_A00689_0804_BHY7FFDRX2/SampleSheet.csv
  tests/fixtures/apps/demultiplexing/flow_cells/170517_ST-E00266_0210_BHJCFFALXX/SampleSheet.csv
  tests/fixtures/apps/demultiplexing/flow_cells/180508_ST-E00269_0269_AHL32LCCXY/SampleSheet.csv
  tests/fixtures/apps/demultiplexing/flow_cells/180509_D00450_0598_BHGYFNBCX2/SampleSheet.csv
  tests/fixtures/apps/demultiplexing/flow_cells/181005_D00410_0735_BHM2LNBCX2/SampleSheet.csv
  tests/fixtures/apps/demultiplexing/flow_cells/211101_A00187_0615_AHLG5GDRZZ/SampleSheet.csv
  tests/fixtures/apps/demultiplexing/flow_cells/230912_A00187_1009_AHK33MDRX3/SampleSheet.csv
  tests/fixtures/apps/demultiplexing/flow_cells_demux_all/211101_A00187_0615_AHLG5GDRZZ/SampleSheet.csv
  tests/fixtures/apps/demultiplexing/sample_sheets/novaseq_6000_sample_sheet_with_reversed_cycles.csv
  tests/fixtures/apps/demultiplexing/sample_sheets/novaseq_x_sample_sheet_with_forward_cycles.csv
  tests/meta/demultiplex/conftest.py
  tests/meta/demultiplex/test_demux_post_processing.py
  tests/meta/demultiplex/test_housekeeper_storage_functions.py
Labels: demultiplex

#2976 Use correct cases in the order_case table
  cg/server/api.py
  cg/services/orders/order_service.py
Labels: Bug

#2979 Refactor sql filters
  cg/store/base.py
  cg/store/crud/delete.py
  cg/store/crud/read.py
  cg/store/filters/status_analysis_filters.py
  cg/store/filters/status_application_filters.py
  cg/store/filters/status_application_limitations_filters.py
  cg/store/filters/status_application_version_filters.py
  cg/store/filters/status_bed_filters.py
  cg/store/filters/status_bed_version_filters.py
  cg/store/filters/status_case_filters.py
  cg/store/filters/status_case_sample_filters.py
  cg/store/filters/status_collaboration_filters.py
  cg/store/filters/status_customer_filters.py
  cg/store/filters/status_flow_cell_filters.py
  cg/store/filters/status_invoice_filters.py
  cg/store/filters/status_metrics_filters.py
  cg/store/filters/status_order_filters.py
  cg/store/filters/status_organism_filters.py
  cg/store/filters/status_panel_filters.py
  cg/store/filters/status_pool_filters.py
  cg/store/filters/status_sample_filters.py
  cg/store/filters/status_user_filters.py
  tests/store/filters/test_status_bed_filters.py
  tests/store/filters/test_status_bed_version_filters.py
  tests/store/filters/test_status_case_sample_filters.py
Labels: Enhancement

#2991 Add downsampled case to same order as original
  cg/models/downsample/downsample_data.py
  tests/conftest.py
Labels: Bug

#2980 Refactor pipeline to workflow in database analysis table
  alembic/versions/2024_02_25_e6e6ead5b0c2_rename_analysis_pipeline_to_workflow.py
  cg/cli/clean.py
  cg/cli/get.py
  cg/meta/report/report_api.py
  cg/meta/upload/gt.py
  cg/meta/upload/scout/uploadscoutapi.py
  cg/models/report/report.py
  cg/server/admin.py
  cg/store/crud/create.py
  cg/store/crud/read.py
  cg/store/filters/status_analysis_filters.py
  cg/store/models.py
  tests/cli/get/test_cli_get_analysis.py
  tests/cli/upload/test_cli_upload_fastq.py
  tests/cli/workflow/rnafusion/test_cli_rnafusion_store_housekeeper.py
  tests/meta/report/test_report_api.py
  tests/meta/upload/scout/conftest.py
  tests/meta/upload/scout/test_generate_load_config.py
  tests/store/crud/read/test_read.py
  tests/store/crud/read/test_read_analysis.py
  tests/store/crud/read/test_read_case.py
  tests/store_helpers.py
  tests/utils/test_dispatcher.py
Labels: Enhancement

#2912 (feat taxprofiler): Add report-deliver
  cg/cli/workflow/nf_analysis.py
  cg/cli/workflow/rnafusion/base.py
  cg/cli/workflow/taxprofiler/base.py
  cg/meta/workflow/nf_analysis.py
  cg/meta/workflow/rnafusion.py
  cg/meta/workflow/taxprofiler.py
  cg/models/nf_analysis.py
  cg/models/taxprofiler/taxprofiler.py
  cg/resources/__init__.py
  cg/resources/taxprofiler_bundle_filenames.csv
  tests/cli/workflow/conftest.py
  tests/cli/workflow/nf_analysis/test_cli_report_deliver.py
  tests/cli/workflow/rnafusion/conftest.py
  tests/cli/workflow/rnafusion/test_cli_rnafusion_report_deliver.py
  tests/conftest.py
  tests/meta/workflow/test_nf_analysis.py
Labels: cg, taxprofiler

#3006 Fix handle pre-existing ticket
  cg/exc.py
  cg/server/api.py
  cg/services/orders/order_service/order_service.py
  cg/store/crud/read.py
  cg/store/filters/status_order_filters.py
Labels: Bug
