Repository Clinical-Genomics/cg, pull requests merged in 2024-07, with the labels that each got.

#3306 add view of Illumina Flow Cell
  cg/server/admin.py
  cg/server/app.py
  cg/store/models.py
Labels: Project Task

#3273 Add Illumina sample sequencing metrics admin view table
  cg/server/admin.py
  cg/server/app.py
  cg/server/auto.py
Labels: Project Task

#3383 Refactor master list usage
  cg/constants/gene_panel.py
  cg/meta/upload/scout/mip_config_builder.py
  cg/meta/workflow/analysis.py
  tests/meta/workflow/test_analysis.py
Labels: Enhancement

#3308 Add HiFi metric parser for PacBio
  cg/constants/pacbio.py
  cg/services/pacbio/metrics/metrics_parser.py
  cg/services/pacbio/metrics/models.py
  tests/conftest.py
  tests/fixture_plugins/pacbio_fixtures/metrics_fixtures.py
  tests/fixture_plugins/pacbio_fixtures/name_fixtures.py
  tests/fixture_plugins/pacbio_fixtures/path_fixtures.py
  tests/fixture_plugins/pacbio_fixtures/service_fixtures.py
  tests/fixtures/devices/pacbio/SMRTcells/r84202_20240522_133539/1_A01/statistics/adapter.report.json
  tests/fixtures/devices/pacbio/SMRTcells/r84202_20240522_133539/1_A01/statistics/ccs.report.json
  tests/fixtures/devices/pacbio/SMRTcells/r84202_20240522_133539/1_A01/statistics/control.report.json
  tests/fixtures/devices/pacbio/SMRTcells/r84202_20240522_133539/1_A01/statistics/loading.report.json
  tests/fixtures/devices/pacbio/SMRTcells/r84202_20240522_133539/1_A01/statistics/raw_data.report.json
  tests/services/pacbio_services/pacbio_metrics_service/test_pacbio_metrics_service.py
Labels: Project Task

#3423 add foreign key constraint sample run metrics to sample
  alembic/versions/2024_07_11_0808675ad136_add_sample_fk.py
Labels: alembic migration

#3474 Add pacbio sample metrics model
  alembic/versions/2024_07_29_77a75121be31_add_pacbio_sample_metrics.py
  cg/store/models.py
Labels: alembic migration

#3468 Add analysis comment column
  alembic/versions/2024_07_29_0ca61967d364_add_comment_column_to_analysis_table.py
  cg/meta/report/report_api.py
  cg/meta/report/templates/macros/data_analysis/data_analysis.html
  cg/models/report/report.py
  cg/server/admin.py
  cg/store/models.py
Labels: alembic migration
