Repository Clinical-Genomics/cg, pull requests merged in 2024-01, with the labels that each got.

#2802 Add OPTIC panel to scout panels masterlist
  cg/constants/gene_panel.py
Labels: Scout, Gain L, Effort S, Customer request

#2788 feat(sql): Refactor addhandler
  cg/store/api/core.py
  cg/store/crud/__init__.py
  cg/store/crud/create.py
  poetry.lock
  pyproject.toml
Labels: Enhancement

#2806 fix sample sheet validation
  cg/cli/demultiplex/demux.py
  cg/models/flow_cell/flow_cell.py
  tests/cli/demultiplex/test_demultiplex_flowcell.py
Labels: demultiplex

#2841 refactor - Organise lims samples fixtures
  tests/apps/demultiplex/conftest.py
  tests/apps/demultiplex/test_sample_models.py
  tests/apps/demultiplex/test_sample_sheet_creator.py
  tests/apps/demultiplex/test_sample_sheet_creator_factory.py
  tests/cli/demultiplex/test_create_sample_sheet.py
  tests/fixture_plugins/demultiplex_fixtures/flow_cell_fixtures.py
  tests/fixture_plugins/demultiplex_fixtures/path_fixtures.py
  tests/fixture_plugins/demultiplex_fixtures/sample_fixtures.py
  tests/fixtures/apps/demultiplexing/flow_cells/190927_A00689_0069_BHLYWYDSXX/HLYWYDSXX_bcl2fastq_raw.json
  tests/fixtures/apps/demultiplexing/flow_cells/190927_A00689_0069_BHLYWYDSXX/HLYWYDSXX_bcl_convert_raw.json
  tests/fixtures/apps/demultiplexing/flow_cells/190927_A00689_0069_BHLYWYDSXX/README.txt
  tests/fixtures/apps/demultiplexing/flow_cells/230912_A00187_1009_AHK33MDRX3/HK33MDRX3_bcl_convert_raw.json
  tests/fixtures/apps/demultiplexing/flow_cells/230912_A00187_1009_AHK33MDRX3/README.txt
Labels: Refactor, demultiplex

#2831 fest(sql): Refactor handler
  cg/cli/workflow/mutant/base.py
  cg/store/api/core.py
  cg/store/crud/read.py
  tests/cli/workflow/conftest.py
  tests/cli/workflow/mip/conftest.py
Labels: Enhancement

#2843 Remove constant DRAGEN and replace usages for BCLCONVERT
  cg/apps/demultiplex/demultiplex_api.py
  cg/apps/demultiplex/sbatch.py
  cg/apps/sequencing_metrics_parser/api.py
  cg/constants/bcl_convert_metrics.py
  cg/constants/demultiplexing.py
  cg/models/flow_cell/flow_cell.py
  tests/apps/demultiplex/test_sample_sheet_creator_factory.py
  tests/cli/demultiplex/test_create_sample_sheet.py
  tests/cli/demultiplex/test_demultiplex_flowcell.py
  tests/fixture_plugins/demultiplex_fixtures/flow_cell_fixtures.py
  tests/meta/demultiplex/conftest.py
  tests/meta/demultiplex/test_demux_post_processing.py
  tests/models/flow_cell/test_flowcell_model.py
Labels: demultiplex

#2862 Bump jinja2 3.1.2 to 3.1.3
  poetry.lock
  pyproject.toml
Labels: dependencies

#2865 Fix clean fc no bundles
  cg/meta/clean/clean_flow_cells.py
  tests/meta/clean/conftest.py
  tests/meta/clean/test_clean_flow_cells_api.py
Labels: Bug

#2867 Make hamming distance calculation different for i7 and i5
  cg/apps/demultiplex/sample_sheet/index.py
  cg/apps/demultiplex/sample_sheet/sample_models.py
  cg/apps/demultiplex/sample_sheet/sample_sheet_creator.py
  tests/apps/demultiplex/test_index.py
  tests/apps/demultiplex/test_sample_models.py
Labels: demultiplex

#2868 Add orders endpoint
  cg/server/api.py
  cg/server/dto/__init__.py
  cg/server/dto/orders/__init__.py
  cg/server/dto/orders/orders_request.py
  cg/server/dto/orders/orders_response.py
  cg/services/orders/__init__.py
  cg/services/orders/order_service.py
  cg/services/orders/utils.py
  cg/store/crud/read.py
  tests/server/conftest.py
  tests/server/endpoints/test_orders_endpoint.py
  tests/store/crud/conftest.py
  tests/store/crud/read/test_read.py
  tests/store_helpers.py
Labels: Streamline Delivery

#2870 Modify Order table
  alembic/versions/2024_01_25_d241d8c493fb_add_pipeline_to_order.py
  cg/server/api.py
  cg/server/dto/orders/orders_response.py
  cg/services/orders/order_service.py
  cg/services/orders/utils.py
  cg/store/models.py
  tests/server/conftest.py
  tests/store/crud/read/test_read.py
  tests/store_helpers.py
Labels: Streamline Delivery

#2701 (feat taxprofiler) Add metrics-deliver
  cg/cli/workflow/nf_analysis.py
  cg/cli/workflow/rnafusion/base.py
  cg/cli/workflow/taxprofiler/base.py
  cg/constants/constants.py
  cg/constants/nf_analysis.py
  cg/constants/rnafusion.py
  cg/meta/workflow/nf_analysis.py
  cg/meta/workflow/rnafusion.py
  cg/meta/workflow/taxprofiler.py
  cg/models/taxprofiler/taxprofiler.py
  tests/cli/workflow/nf_analysis/test_cli_metrics_deliver.py
  tests/cli/workflow/rnafusion/test_cli_rnafusion_compound_commands.py
  tests/cli/workflow/rnafusion/test_cli_rnafusion_metrics_deliver.py
  tests/cli/workflow/rnafusion/test_cli_rnafusion_report_deliver.py
  tests/cli/workflow/rnafusion/test_cli_rnafusion_run.py
  tests/cli/workflow/taxprofiler/test_cli_taxprofiler_config_case.py
  tests/cli/workflow/taxprofiler/test_cli_taxprofiler_metrics_deliver.py
  tests/conftest.py
  tests/fixtures/analysis/rnafusion/rnafusion_case_enough_reads_metrics_deliverables.yaml
  tests/fixtures/analysis/taxprofiler/multiqc_data.json
  tests/fixtures/analysis/taxprofiler/taxprofiler_case_metrics_deliverables.yaml
  tests/meta/report/test_rnafusion_api.py
  tests/meta/workflow/conftest.py
  tests/meta/workflow/test_nf_analysis.py
  tests/meta/workflow/test_rnafusion.py
Labels: cg, taxprofiler

#2883 feat(sars-cov-2): Remove
  cg/constants/constants.py
  cg/services/delivery_message/utils.py
Labels: Enhancement
